config/routes.rb
DbcRspecRails::Application.routes.draw do
  namespace :admin do
    resources :posts
    resources :sessions, :only => [:new, :create, :destroy]
  end

  resources :posts

  root :to => "home#index"
end

app/models/post.rb
class Post < ActiveRecord::Base

  def self.recent
    order("created_at DESC").limit(5)
  end

  before_save :titleize_title, :generate_slug

  validates :title, :content, :presence => true

  private

  def titleize_title
    self.title = title.titleize
  end

  def generate_slug
    self.slug = title.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  before_save :set_name_from_email

  private

  def set_name_from_email
    self.name = email.sub(/@.+/, '')
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_filter :authorize_user!
  before_filter :load_post, :only => [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "Post was successfully saved."
      redirect_to admin_post_path(@post)
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to admin_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :is_published)
  end
  def load_post
    @post = Post.find(params[:id])
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      login @user
      redirect_to root_path
    else
      flash[:notice] = "Bad email/password combination"
      redirect_to new_admin_session_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @user ||= User.find session[:user_id] if session[:user_id]
    p @user
  end

  def authorize_user!
    redirect_to new_admin_session_path unless current_user.present?
  end

  def login user
    session[:user_id] = user.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_posts = Post.recent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <%= f.text_field :title, :placeholder => 'Title' %>
  <%= f.text_area :content, :placeholder => 'Content' %>
  Publish? <%= f.check_box :is_published %>
  <%= f.submit "Save" %>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>
<%= render "form" %>

app/views/admin/posts/index.html.erb
<h1>Welcome to the admin panel!</h1>

<%= link_to "New Post", new_admin_post_path %>

<% if @posts.any? %>
  <h4>All posts:</h4>
  <table>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <%= link_to "Edit", edit_admin_post_path(post) %>
          <%= link_to "Delete", admin_post_path(post), :method => :delete, :confirm => "Are you sure you want to delete this post?" %>
        </td>
      </tr>
    <% end %>
  </table
<% end %>

app/views/admin/posts/new.html.erb
<h1>New post</h1>
<%= render "form" %>

app/views/admin/posts/show.html.erb
<%= link_to "Admin welcome page", admin_posts_path %>
<%= link_to "Edit post", edit_admin_post_path(@post) %>
<h1><%= link_to @post.title, post_path(@post), id:"post#{@post.id}" %> </h1>
Published: <%= @post.is_published? %>
<%= simple_format @post.content %>

app/views/home/index.html.erb
<H1>Welcome to my blog!</h1>

<%= link_to "View All Posts", posts_path, :class => 'sweet-link', :id => 'sweet_link', :"data-anything" => "anything" %>

<% if @recent_posts.any? %>
  <h4>Recent Posts:</h4>
  <ul>
    <% @recent_posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <p><%= flash[:notice] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcRspecRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <h4><%= post.title %></h4>
    <%= simple_format post.content %>
    <hr>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= simple_format @post.content %>